terraform {
  required_providers {
    azapi = {
      source = "Azure/azapi"
    }
  }
}

provider "azapi" {
  skip_provider_registration = false
}

resource "azapi_resource" "resourceGroup" {
  type      = "Microsoft.Resources/resourceGroups@2020-06-01"
  parent_id = "/subscriptions/85b3dbca-5974-4067-9669-67a141095a76"
  name      = "acctest-rg-221102104453170698"
  location  = "westeurope"
  body      = jsonencode({})
  tags      = {}
}

resource "azapi_resource" "grafana" {
  type      = "Microsoft.Dashboard/grafana@2022-08-01"
  parent_id = azapi_resource.resourceGroup.id
  name      = "a-dg-221102104453170698"
  location  = azapi_resource.resourceGroup.location
  identity {
    type         = "SystemAssigned"
    identity_ids = []
  }
  body = jsonencode({
    properties = {
      apiKey                            = "Enabled"
      autoGeneratedDomainNameLabelScope = "TenantReuse"
      deterministicOutboundIP           = "Enabled"
      publicNetworkAccess               = "Disabled"
      zoneRedundancy                    = "Disabled"
    }
    sku = {
      name = "Standard"
    }
  })
  tags = {
    key = "value"
  }
}

resource "azapi_resource" "grafana2" {
  type      = "Microsoft.Dashboard/grafana@2022-08-01"
  parent_id = azapi_resource.resourceGroup.id
  name      = "a-dg-221102104453170698"
  location  = azapi_resource.resourceGroup.location
  identity {
    type         = "SystemAssigned"
    identity_ids = []
  }
  body = jsonencode({
    id = "/subscriptions/85b3dbca-5974-4067-9669-67a141095a76/resourceGroups/acctest-rg-221102104453170698/providers/Microsoft.Dashboard/grafana/a-dg-221102104453170698"
    properties = {
      apiKey                            = "Disabled"
      autoGeneratedDomainNameLabelScope = "TenantReuse"
      deterministicOutboundIP           = "Disabled"
      provisioningState                 = "Succeeded"
      publicNetworkAccess               = "Enabled"
      zoneRedundancy                    = "Disabled"
    }
    sku = {
      name = "Standard"
    }
  })
  tags = {
    key2 = "value2"
  }
}
